sonar.organization=mayankbishtt
sonar.projectKey=mayankbishtt_ai-self-healing-devops-platform

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.12

sonar.exclusions=venv/**,.terraform/**,terraform/aws/.terraform/**,docs/**

sonar.test.inclusions=tests/**/*.py