apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mayankbishtt/ai-self-healing-devops-platform.git
    targetRevision: gitops
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-app

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true